version: 2
project_name: mon
builds:
  - id: mon
    main: .
    binary: mon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - arm64
      - amd64
    ignore:
      - goos: darwin
        goarch: '386'
    ldflags:
      - -s -w -X github.com/cneill/mon/internal/version.Version={{.Version}} -X github.com/cneill/mon/internal/version.Commit={{.ShortCommit}} -X github.com/cneill/mon/internal/version.Date={{.Date}}
archives:
  - id: mon
    ids:
      - mon
    formats:
      - tar.gz
    files:
      - ./README.md
      - ./LICENSE
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github-native
  abbrev: 0
  sort: asc
