version: 2
project_name: mon
builds:
  - id: mon
    main: .
    binary: mon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    # ignore:
    #   - goos: darwin
    #     goarch: '386'
    ldflags:
      - -s -w -X github.com/cneill/mon/internal/version.Version={{.Version}} -X github.com/cneill/mon/internal/version.Commit={{.ShortCommit}} -X github.com/cneill/mon/internal/version.Date={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
archives:
  - id: mon
    ids:
      - mon
    formats:
      - tar.gz
    files:
      - ./README.md
      - ./LICENSE
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github-native
  abbrev: 0
  sort: asc
